Using MGR as the execution fee in the Mangata demo
OAK-Foundation/xcm-demo pull request #102
Opened 2023-12-04 13:27 UTC by imstar15

We can use MGR as the scheduled fee and execution fee.

```
? Select an action to perform Execute immediately
Initializing adapters of both chains ...
2023-12-07 13:30:04        API/INIT: RPC methods not decorated: automationPrice_queryFeeDetails
2023-12-07 13:30:04        API/INIT: turing/296: Not decorating unknown runtime apis: AutomationPriceApi/1
? Select a asset as the schedule fee for the task MGR
? Select a asset as the execution fee for XCM MGR
1. Reading assets ...

2. Add a proxy on Mangata for paraId 2114, or skip this step if that exists ...
Proxy array of 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY is empty ...
Adding a proxy for paraId 2114. Proxy address: 5GVfCUemHznsgmQxgoKiZNfnkVcLAbgiKakVtgpwQHKmXHiq ...
status.type Ready
2023-12-07 13:30:24        API/UTIL: block 0x67b95d36eddf5aad3c67271bfeb0e02d96a315cd2b39a4f19eb7c776ba515176: Unable to find extrinsic 0x0ff0472bbf7913a01639c2d0bc5a9e155aad44470f6d920ec9ed522f3be17fb0 inside 0x9093f021ded136844edb85587afbd7be058def410d17e1010d2e29aa9463b483, 0xe72c539bb3c9ed3bacdeca49371e018bf2bd920c2bf08ed54a862885f01e3371, 0xad66f24341c74688732c538a44739b7f3649a7ad480f890f0d5b72a8364286b4
status.type InBlock
status.type InBlock
status.type Finalized
? 
Account balance check is completed and proxy is set up. Press ENTRE to mint MGR-TUR. yes
shouldMintLiquidity:  true
Checking how much reward available in MGR-TUR pool, tokenId: 9 ...
Claimable reward in MGR-TUR:  102
Before auto-compound, Alice reserved "MGR-TUR": 492 ...
? 
Do you want to continue to schedule auto-compound. Press ENTRE to continue. yes

4. Check if It's need to send foreign token to Turing ...
Send MGR to Turing...
Transfer from mangata-local, extrinsic: 0x32010300010200f920060400000000000000000000000000000000000000000000000000000000000000000017000010632d5ec76b050301020009210100d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d00
status.type Ready
2023-12-07 13:31:00        API/UTIL: block 0xcada1b286496dc13cb10063ec158580b984e28de0f88a63c9e56aec960de09b4: Unable to find extrinsic 0x1a5636809b611f8b3ec82a1aa8cfd4743e2f849d38c01bf6bd3711bbe8188675 inside 0xa36fd39bafd02980a5476e24128fb629de296b10cb57cac0bde9828225604fb7, 0xebd6c875e654c98c24e1d854a9a0a7ad32a7c3fd3a8e4dc5d3db227585d4ba82, 0x86a341f7c796812a072e40326155e75bd43c2962fb2eb8504ff3c9c2c0f8243a
status.type InBlock
status.type InBlock
status.type Finalized

5. Start to schedule an auto-compound call via XCM ...
Send extrinsic from turing-local to schedule task. extrinsic: 0x3c020004000000000000000003010100f92003010200f9200604000000000000000000000000000000000000000000000000000000000000000003010200f920060400000000000000000000000000000000000000000000000000000000000000003a44d0e849b5c0780300000000000000bc050000d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d01000d08090000001027000003b7dd2cad113a03b7c6d1e2113a
status.type Ready
status.type InBlock
status.type Finalized
        proxy:ProxyExecuted:: (phase={"applyExtrinsic":0})
                        Result<Null, SpRuntimeDispatchError>: Ok
Retrieved taskId 223-2-3 from TaskScheduled among the finalized events.

5. Keep Listening XCM events on mangata-local until 2023-12-07 13:40:00(1701927600) to verify that the task(taskId: 223-2-3) will be successfully executed ...
Task has been executed!

Waiting 20 seconds before reading new chain states ...

After auto-compound, reserved MGR-TUR is: 492505347998381370837 planck ...
Alice has compounded 505347506381370837 planck more MGR-TUR ...
Reached the end of main() ...
```

2023-12-06 19:46 UTC, chrisli30 requested changes

2023-12-07 05:34 UTC, imstar15 commented on src/common/utils.js
> +};
Fixed

2023-12-07 06:51 UTC, chrisli30 approved these changes
Looks good 👌

2023-12-07 06:51 UTC, chrisli30 commented on src/mangata/common.js
> +            if (scheduleFeeAsset === mangataDefaultAsset || executionFeeAsset === mangataDefaultAsset) {
You are comparing two objects, which is not safe in javascript. It’s better to company their keys, which are strings.

2023-12-07 07:01 UTC, merged