Send XCM to call the contract on Moonbase
OAK-Foundation/xcm-demo pull request #43
Opened 2023-03-13 13:18 UTC by imstar15

2023-03-14 22:17 UTC, chrisli30 commented on src/moonbeam/test-moonbase-contract/index.js
> +});
@imstar15 Let’s add your instructions from Slack to the README.md at the root level.

2023-03-16 21:15 UTC, chrisli30 commented on src/common/utils.js
> +    };
👍

2023-04-23 19:31 UTC, chrisli30 approved these changes
Local testing passed with Moonbase runtime 2201. Good to merge.

2023-04-23 22:15 UTC, chrisli30 requested changes
这代码质量标准太低了，问题包括但不限于，
各种hard-code
代码复用严重
代码顺序混乱，上下文没联系的代码堆在一起
变量命名歧义导致逻辑混乱，为什么图灵上的wallet叫moonbaseKeyPair？

2023-04-24 03:23 UTC, chrisli30 commented
Rebased master with a force push.

2023-04-24 03:44 UTC, imstar15 commented on src/moonbeam/moonbase-alpha.js
> +const CONTRACT_ADDRESS = '0xa72f549a1a12b9b49f30a7f3aeb1f4e96389c5d8';
Yes!
Please use the Incrementer contract address.

2023-04-24 03:56 UTC, imstar15 commented on src/moonbeam/test-moonbase-contract/index.js
> +});
It used to test the Increment contract.

I'll add some text to the README to explain it.

**Usage:**

```
CONTRACT_ADDRESS=<CONTRACT_ADDRESS> npm run test-moonbase-contract
```

2023-05-08 18:00 UTC, chrisli30 commented on src/moonbeam/moonbase-local.js
> +    const topUpAmount = (new BN(1000000).mul(decimalBN)).toString();
What is the reason for the increment? We can’t create a proxy with 1000 DEV any more?

2023-05-08 21:57 UTC, chrisli30 commented on package.json
> +    "@oak-network/types": "^1.8.1-rc.1",
@imstar15 We need to make these libraries official v1.8.1 and reference them.

2023-05-09 04:46 UTC, chrisli30 approved these changes

2023-05-09 04:46 UTC, merged