Update Mangata-rococo and Mangata-kusama tests with oak-blockchain v2.0.0
OAK-Foundation/xcm-demo pull request #79
Opened 2023-08-07 10:35 UTC by imstar15

2023-08-10 18:47 UTC, chrisli30 requested changes

2023-08-11 04:18 UTC, imstar15 commented on src/mangata/common.js
> +                console.log('Find TaskScheduled event in extrinsic events.');
The task ID is retrieved from the TaskScheduled event within the extrinsic. The extrinsic does not have a response.

2023-08-11 18:50 UTC, chrisli30 commented on src/mangata/common.js
> +                console.log('Find TaskScheduled event in extrinsic events.');
I looked up the code. The TaskScheduled is included in the isFinalized response.

2023-08-11 18:53 UTC, chrisli30 approved these changes

2023-08-11 18:53 UTC, chrisli30 commented on src/mangata/common.js
> +                console.log('Find TaskScheduled event in extrinsic events.');
I have updated the console log message below.

2023-08-11 18:53 UTC, merged